services:
  - type: web
    name: askthebook
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    disk:
      name: chroma-storage
      mountPath: /opt/render/project/src/chroma_db
      sizeGB: 1
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: SCALEDOWN_API_KEY
        sync: false
      - key: CHROMA_PATH
        value: /opt/render/project/src/chroma_db